export const COUNTRY_OPTIONS = [
  { code: "+52", es: "México", en: "Mexico" },
  { code: "+1", es: "Estados Unidos / Canadá", en: "United States / Canada" },
  { code: "+34", es: "España", en: "Spain" },
  { code: "+54", es: "Argentina", en: "Argentina" },
  { code: "+55", es: "Brasil", en: "Brazil" },
  { code: "+56", es: "Chile", en: "Chile" },
  { code: "+57", es: "Colombia", en: "Colombia" },
  { code: "+51", es: "Perú", en: "Peru" },
  { code: "+58", es: "Venezuela", en: "Venezuela" },
  { code: "+593", es: "Ecuador", en: "Ecuador" },
  { code: "+591", es: "Bolivia", en: "Bolivia" },
  { code: "+595", es: "Paraguay", en: "Paraguay" },
  { code: "+598", es: "Uruguay", en: "Uruguay" },
  { code: "+502", es: "Guatemala", en: "Guatemala" },
  { code: "+503", es: "El Salvador", en: "El Salvador" },
  { code: "+504", es: "Honduras", en: "Honduras" },
  { code: "+505", es: "Nicaragua", en: "Nicaragua" },
  { code: "+506", es: "Costa Rica", en: "Costa Rica" },
  { code: "+507", es: "Panamá", en: "Panama" },
  { code: "+53", es: "Cuba", en: "Cuba" },
  { code: "+1-809", es: "República Dominicana", en: "Dominican Republic" },
  { code: "+1-787", es: "Puerto Rico", en: "Puerto Rico" },
  { code: "+44", es: "Reino Unido", en: "United Kingdom" },
  { code: "+33", es: "Francia", en: "France" },
  { code: "+49", es: "Alemania", en: "Germany" },
  { code: "+39", es: "Italia", en: "Italy" },
  { code: "+351", es: "Portugal", en: "Portugal" },
  { code: "+31", es: "Países Bajos", en: "Netherlands" },
  { code: "+32", es: "Bélgica", en: "Belgium" },
  { code: "+41", es: "Suiza", en: "Switzerland" },
  { code: "+43", es: "Austria", en: "Austria" },
  { code: "+46", es: "Suecia", en: "Sweden" },
  { code: "+47", es: "Noruega", en: "Norway" },
  { code: "+45", es: "Dinamarca", en: "Denmark" },
  { code: "+358", es: "Finlandia", en: "Finland" },
  { code: "+353", es: "Irlanda", en: "Ireland" },
  { code: "+30", es: "Grecia", en: "Greece" },
  { code: "+48", es: "Polonia", en: "Poland" },
  { code: "+420", es: "República Checa", en: "Czech Republic" },
  { code: "+40", es: "Rumania", en: "Romania" },
  { code: "+90", es: "Turquía", en: "Turkey" },
  { code: "+380", es: "Ucrania", en: "Ukraine" },
  { code: "+7", es: "Rusia / Kazajistán", en: "Russia / Kazakhstan" },
  { code: "+86", es: "China", en: "China" },
  { code: "+81", es: "Japón", en: "Japan" },
  { code: "+82", es: "Corea del Sur", en: "South Korea" },
  { code: "+91", es: "India", en: "India" },
  { code: "+92", es: "Pakistán", en: "Pakistan" },
  { code: "+880", es: "Bangladesh", en: "Bangladesh" },
  { code: "+63", es: "Filipinas", en: "Philippines" },
  { code: "+62", es: "Indonesia", en: "Indonesia" },
  { code: "+60", es: "Malasia", en: "Malaysia" },
  { code: "+65", es: "Singapur", en: "Singapore" },
  { code: "+66", es: "Tailandia", en: "Thailand" },
  { code: "+84", es: "Vietnam", en: "Vietnam" },
  { code: "+61", es: "Australia", en: "Australia" },
  { code: "+64", es: "Nueva Zelanda", en: "New Zealand" },
  { code: "+971", es: "Emiratos Árabes Unidos", en: "United Arab Emirates" },
  { code: "+966", es: "Arabia Saudita", en: "Saudi Arabia" },
  { code: "+972", es: "Israel", en: "Israel" },
  { code: "+20", es: "Egipto", en: "Egypt" },
  { code: "+27", es: "Sudáfrica", en: "South Africa" },
  { code: "+234", es: "Nigeria", en: "Nigeria" },
  { code: "+254", es: "Kenia", en: "Kenya" },
  { code: "+212", es: "Marruecos", en: "Morocco" },
  { code: "+216", es: "Túnez", en: "Tunisia" },
];

const COUNTRY_FLAG_BY_CODE: Record<string, string> = {
  "+52": "🇲🇽",
  "+1": "🇺🇸",
  "+34": "🇪🇸",
  "+54": "🇦🇷",
  "+55": "🇧🇷",
  "+56": "🇨🇱",
  "+57": "🇨🇴",
  "+51": "🇵🇪",
  "+58": "🇻🇪",
  "+593": "🇪🇨",
  "+591": "🇧🇴",
  "+595": "🇵🇾",
  "+598": "🇺🇾",
  "+502": "🇬🇹",
  "+503": "🇸🇻",
  "+504": "🇭🇳",
  "+505": "🇳🇮",
  "+506": "🇨🇷",
  "+507": "🇵🇦",
  "+53": "🇨🇺",
  "+1-809": "🇩🇴",
  "+1-787": "🇵🇷",
  "+44": "🇬🇧",
  "+33": "🇫🇷",
  "+49": "🇩🇪",
  "+39": "🇮🇹",
  "+351": "🇵🇹",
  "+31": "🇳🇱",
  "+32": "🇧🇪",
  "+41": "🇨🇭",
  "+43": "🇦🇹",
  "+46": "🇸🇪",
  "+47": "🇳🇴",
  "+45": "🇩🇰",
  "+358": "🇫🇮",
  "+353": "🇮🇪",
  "+30": "🇬🇷",
  "+48": "🇵🇱",
  "+420": "🇨🇿",
  "+40": "🇷🇴",
  "+90": "🇹🇷",
  "+380": "🇺🇦",
  "+7": "🇷🇺",
  "+86": "🇨🇳",
  "+81": "🇯🇵",
  "+82": "🇰🇷",
  "+91": "🇮🇳",
  "+92": "🇵🇰",
  "+880": "🇧🇩",
  "+63": "🇵🇭",
  "+62": "🇮🇩",
  "+60": "🇲🇾",
  "+65": "🇸🇬",
  "+66": "🇹🇭",
  "+84": "🇻🇳",
  "+61": "🇦🇺",
  "+64": "🇳🇿",
  "+971": "🇦🇪",
  "+966": "🇸🇦",
  "+972": "🇮🇱",
  "+20": "🇪🇬",
  "+27": "🇿🇦",
  "+234": "🇳🇬",
  "+254": "🇰🇪",
  "+212": "🇲🇦",
  "+216": "🇹🇳",
};

export const compactCountryDialLabel = (code: string) => {
  const flag = COUNTRY_FLAG_BY_CODE[code] || "🌐";
  return `${flag} ${code}`;
};
